### ISSUE TITLE
CRASH when play music

### ISSUE THREAD

**Issue by kyzsuukii** [AP-Atul/music_player_lite#23]
this is log when crashed:

![Screenshot_2022-12-20-23-13-09-539_com.fei_ke.crashreport.jpg](https://user-images.githubusercontent.com/110718021/208728954-7e07bd2e-154d-4e75-9e47-17f0a42a91aa.jpg)

```
Version Name: 0.12
Version Code: 12

java.lang.SecurityException: External path: /storage/emulated/0/Android/data/com.android.providers.media/albumthumbs/1671488722319: Neither user 10072 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1473)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1310)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1163)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1117)
	at i1.b.b(Unknown Source:11)
	at l1.b.a(SourceFile:4)
	at com.atul.musicplayer.player.b.onPrepared(Unknown Source:7)
	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3441)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6820)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)

```

**Comment by AP-Atul** [comment]
I'm not able to recreate this. As the error says, it is about the WRITE Permission, but the version you are using does not require that permission so I removed it, there is no situation when there are any write operations.
